from __future__ import annotations

from pathlib import Path

NUM_FRAMES = 4
PLANET_SLOTS = 44
ACTIONS_DIM = 7
TOKEN_DIM = 11
GLOBAL_DIM = 16

ACTION_CHOICES_PER_SOURCE = PLANET_SLOTS * ACTIONS_DIM
ACTION_DIMS = [ACTION_CHOICES_PER_SOURCE] * PLANET_SLOTS

TOKEN_SHAPE = (NUM_FRAMES, PLANET_SLOTS, TOKEN_DIM)
PRESENCE_SHAPE = (NUM_FRAMES, PLANET_SLOTS)
TURN_SHAPE = (NUM_FRAMES, PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)
ACTION_TENSOR_SHAPE = (PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)

TRAIN_DIR = Path(__file__).resolve().parent
EXPERIMENTAL_ARCH_DIR = TRAIN_DIR.parent
REPO_ROOT = TRAIN_DIR.parents[1]
BOTS_DIR = REPO_ROOT / "bots"
