from __future__ import annotations

from pathlib import Path

NUM_FRAMES = 4
PLANET_SLOTS = 44
ACTIONS_DIM = 2
NOOP_CHOICE = 0
SEND_ALL_ACTION = 1
LAUNCH_GATE_CHOICES = 2
TARGET_CHOICES = PLANET_SLOTS
TOKEN_DIM = 11
GLOBAL_DIM = 16

ACTION_CHOICES_PER_SOURCE = LAUNCH_GATE_CHOICES + TARGET_CHOICES
# Per source: [noop/send gate, target slot]. The target is ignored when the
# gate chooses noop; this keeps launch/noop as a true binary decision.
ACTION_DIMS = [
    choice
    for _ in range(PLANET_SLOTS)
    for choice in (LAUNCH_GATE_CHOICES, TARGET_CHOICES)
]

TOKEN_SHAPE = (NUM_FRAMES, PLANET_SLOTS, TOKEN_DIM)
PRESENCE_SHAPE = (NUM_FRAMES, PLANET_SLOTS)
TURN_SHAPE = (NUM_FRAMES, PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)
ACTION_TENSOR_SHAPE = (PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)
POLICY_MASK_SHAPE = (PLANET_SLOTS, ACTION_CHOICES_PER_SOURCE)

TRAIN_DIR = Path(__file__).resolve().parent
EXPERIMENTAL_ARCH_DIR = TRAIN_DIR.parent
REPO_ROOT = TRAIN_DIR.parents[1]
BOTS_DIR = REPO_ROOT / "bots"
