from __future__ import annotations

from pathlib import Path

NUM_FRAMES = 4
PLANET_SLOTS = 44
ACTIONS_DIM = 3
NOOP_CHOICE = 0
SEND_HALF_ACTION = 1
SEND_ALL_ACTION = 2
LAUNCH_GATE_CHOICES = 3
TARGET_CHOICES = PLANET_SLOTS
TOKEN_DIM = 15
GLOBAL_DIM = 16
PLANET_TIMELINE_DIM = 31
PAIR_OUTCOME_DIM = 4

ACTION_CHOICES_PER_SOURCE = LAUNCH_GATE_CHOICES + TARGET_CHOICES
# Per source: [noop/send-size gate, target slot]. The target is ignored when
# the gate chooses noop.
ACTION_DIMS = [
    choice
    for _ in range(PLANET_SLOTS)
    for choice in (LAUNCH_GATE_CHOICES, TARGET_CHOICES)
]

TOKEN_SHAPE = (NUM_FRAMES, PLANET_SLOTS, TOKEN_DIM)
PRESENCE_SHAPE = (NUM_FRAMES, PLANET_SLOTS)
TURN_SHAPE = (NUM_FRAMES, PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)
PAIR_TURN_SHAPE = (PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)
PLANET_TIMELINE_SHAPE = (PLANET_SLOTS, PLANET_TIMELINE_DIM)
PAIR_OUTCOME_SHAPE = (PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM, PAIR_OUTCOME_DIM)
ACTION_TENSOR_SHAPE = (PLANET_SLOTS, PLANET_SLOTS, ACTIONS_DIM)
POLICY_MASK_SHAPE = (PLANET_SLOTS, ACTION_CHOICES_PER_SOURCE)

TRAIN_DIR = Path(__file__).resolve().parent
EXPERIMENTAL_ARCH_DIR = TRAIN_DIR.parent
REPO_ROOT = TRAIN_DIR.parents[1]
BOTS_DIR = REPO_ROOT / "bots"
